import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import Header from "@/components/header";
import Header2 from "@/components/header2";
import Hero from "@/components/hero";
import Category from "@/components/category";
import Selling from "@/components/selling";
import EasyAndFast from "@/components/easyandfast";
import Testimonial from "@/components/testimonial";
import Logo from "@/components/logo";
import Subscribe from "@/components/subscribe";
import AboveFooter from "@/components/abovefooter";
import Footer from "@/components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Header/> */}
        <Header2/>
        <Hero/>
        <Category/>
        <Selling/>
        <EasyAndFast/>
        <Testimonial/>
        <Logo/>
        <Subscribe/>
        <AboveFooter/>
        <Footer/>
        {children}
      </body>
    </html>
  );
}
